### ISSUE TITLE
Embed 'mixed' mode into IOR

### ISSUE THREAD

**Issue by johnbent** [VI4IO/io-500-dev#4]
Instead of running two IOR jobs concurrently in order to get the 'mixed' number, it might be more precise to run mixed IO directly within IOR.  This might not be worth the complexity.

If we are to decide to do so, the thing to do would be to double up the parameters to IOR (i.e. to simultaneously specify two IO patterns) and then do an MPI_Comm_split on MPI_COMM_WORLD to split the ranks into two groups and then have each group do one pattern (i.e. one hard and one easy).  Then report back the performance for each group as well as the aggregate performance.

**Comment by johnbent** [comment]
I'm closing this for now.  Let's get the current thing up and running for a couple of years before changing the benchmarks.

**Comment by gmarkomanolis** [comment]
It's fine for me but I plan to use the mixed mode in the next weeks for procurement, I think it is quite important for realistic results. When you see the actual results and not the final score, for example, worse and best BW performance, then you miss important information that you get from the mixed mode. By mix mode I mean two applications executed concurrently because this is what happened in reality and it is easy to prepare. Of course, I would not plan metadata tests in mixed mode because the workload on the system could be huge.

**Comment by johnbent** [comment]
Good point. We should do this. Maybe add it as an optional thing and later switch it to required after a few years of stability with current setup.
