### ISSUE TITLE
A couple of considerations for the published lists 

### ISSUE THREAD

**Issue by RayLucchesi** [VI4IO/io-500-dev#76]
Great information but it could be better:
1) There appears to be 4 lists: historical list, ISC High Performance 2020 list, 10 Node list, and Full List. I understand that the 10-node lists only has the top submissions for a 10 node configuration, But the difference between the ISC High Perf (42 entries) , Full list (114 entries) and Historical List (220 entries) is not that Clear. 
2) In addition the number of 10 node submissions on the Full list seems to be a count of 68 but the number of entries on the 10 Node list is 42. I assume this is due to selecting the best submission for a configuration... (see next item)
3) There seem to be multiple entries/submissions for the same configuration, same file system, same everything. I understand that you are allowing this and taking the best of the results. However. It would be useful if each submission were tagged with something akin to an ID (e.g. IO500_ISC20_0003, IO500_ISC20_0004, etc.) that way we could take the full list and understand which of these were incorporated into the sub-lists (Such as the 10-Node).

**Comment by RayLucchesi** [comment]
I need to add another
4) The CSV downloads for each of the lists appear to be a selection that only provides fields in the displayed table. But complete data provides all the information for the submission. However. the complete data is not just the submissions present in the list but rather a full listing. So trying to understand the details (eg. FIND-EASY score) is difficult to see because a) one first has to select just the benchmarks for 10 nodes and then b) somehow figure out which one of the 10 node submissions represents the best for a filesystem...

**Comment by RayLucchesi** [comment]
4A) perhaps this is just an error on the 10 node web page because the Complete data CSV download is the same as the  ISC20 High Performance list and doesn't have all the 37 10 node submissions.

**Comment by gflofst** [comment]
Thank you, Ray, for contacting us. Here is some explanation of why things are done the way they are and how things work:

The four lists are distinct. The “historical” list includes historical entries that are no longer directly comparable due to changes in the benchmark. The “full” list is systems of any size. The “ISC” or “SC” list is the main list for that update. The “10 node challenge” list is for submissions targeted for the special exactly 10 client node tests. This list was created to offer a more apples-to-apples comparison since the system sizes are much more similar and will all ultimately be interconnect limited. The “full” and “ISC” or “SC” may or may not include entries from the “10 node” list, as per the request of the submitter. They have control of how they want their submissions to appear. For some community members, they have requested to not appear on the full list because they know they cannot compete with the top score and their management would feel embarrassed by a low ranking. The “ISC” or “SC” and “10 node challenge” lists are each versioned at our semi-annual list update at ISC and SC each year. Each time a user submits, we maintain all submissions for historical purposes. The list displayed should only include the most recent for each combination (machine, file system, user).

Our composite score is an attempt to balance both the achievable bandwidth against the achievable metadata performance. Many systems are highly skewed in one direction or the other and this combination shows, to a reasonable degree, a balance between the two. It is not perfect, but it is our overall ranking metric. We strongly encourage visitors to re-sort the list according to their own workloads to get something that better fulfills their needs. You can do this by clicking the column title on the web page, or by entering a custom formula using the available fields. As you have discovered, you can also download the csv files or the full submission data to do deeper data analysis.

We have not spent any time breaking apart the fully submitted data into discrete fields and are currently only providing the csv files of the web pages. We do have a student looking at the metadata quality, i.e., what can be derived from it and what does each field mean to submitters. Based on the outcome of that student’s work, we may make broader changes to what we provide pre-parsed into discrete fields for easier analysis. Finding extra time to devote to this all volunteer project is another limiting factor.

If the 10 node csv file is in error, please file a separate error report.

**Comment by RayLucchesi** [comment]
Ok thanks for the info. I opened up a new issue on the 10-node complete CSV file being the wrong list.
Ray

**Comment by gflofst** [comment]
Please re-open if there is more you need to know or open a new issue for other questions.
